### ISSUE TITLE
no puedo abrir los archivos .lat (código latino)

### ISSUE THREAD

**Issue by coderdeluaylat** [MelvinG24/Latino-VS#2]
todo funciona correctamente, incluyendo la aplicación de latino

el único problema es cuando intento abrir un archivo .lat a través del explorador de archivos (un archivo previamente guardado desde visual studio code). latino se cierra en una fracción de segundo sin dar ejecución al código

he intentado varias veces abrir el archivo, pero no logro nada. ¿alguien de casualidad tendrá una solución?

Firma: Jeff

**Comment by MelvinG24** [comment]
Hola @coderdeluaylat,

Disculpa por la larga demora en responder a tu issue. Los issues relacionados con Latino y no con el plugin deverian de ser publicados en el repo de latino [aquí](https://github.com/lenguaje-latino/latino/issues).

De igual manera a mi parecer lo que creo que pasa con tu código es que el mismo se ejecuta y no puedes ver lo que el código hace porque este mismo termina y se cierra la ventana al momento.

Mi recomendación es que le agreges el comando **leer()** al final de tu código, así el programa en vez de cerrar al terminar este esperara a que presiones una tecla para poder continuar, así podrás ver tu código y su resultado.
