### ISSUE TITLE
Compilar el codigo

### ISSUE THREAD

**Issue by ElAmyProgramador** [MelvinG24/Latino-VS#3]
Lo intento usar pero no compila ni ejecuta el codigo, me dice que necesito una extension para depurarlo pero ya la instale, y aun asi no me deja.

![image](https://user-images.githubusercontent.com/91046251/133960925-003ce301-08b8-4701-9712-2cda8e61e23d.png)
![image](https://user-images.githubusercontent.com/91046251/133960939-7c31f2c6-a9b2-4ccb-801a-f1eebce4768a.png)

Firma: Alexeiv

**Comment by MelvinG24** [comment]
Hola @ElAmyProgramador,
Disculpa la demora en responder a tu issue. Actualmente el plugin de Latino para VSCode no soporta ejecuciones en la terminal, para eso tendrías que hacerlo manualmente. Ya en la próxima versión del plugin eso que pides será posible.
