### ISSUE TITLE
Nuevo en esto

### ISSUE THREAD

**Issue by platicadenada** [MelvinG24/Latino-VS#4]
Al querer correo el codigo sencillo de 
Imprimir("jskisi") 
Me marca en ingles en una esquina que no es compatible que puedo hacer para que tido funcione

**Comment by MelvinG24** [comment]
Si te marca algún _mensaje en Ingles_ ya seria porque en ese **Idioma tienes el VSCode**.

Ahora respondiendo a tu pregunta, Latino es **sensible** a las **mayúsculas** y **minúsculas** (_Case sensitive_) o otras palabras el comando` imprimir()`  lo interpretara diferente a si lo escribes con mayúsculas, tal como lo tienes en tu ejemplo
